name: JuvoPlayerFlutter
description: Demonstrates how to use the JuvoPlayer in Flutter.
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.1.0
  video_player_tizen:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/bumble_bee_captions.srt

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
